export const exerciseImages = {
  default: require('./react-logo.png'),
  puxadaPoliaBarra: require('./puxada-polia-barra.png'),
  remadaMaquina: require('./remada-maquina.jpg'),
  crucifixoInverso: require('./crucifixo-inverso.jpg'),
  bicepsMaquina: require('./biceps-maquina.jpg'),
  roscaDiretaHalter: require('./rosca-direta-halter.jpg'),
  abdominalMaquina: require('./abdominal-maquina.jpg'),
  supinoRetoComHalter: require('./supino-reto-com-halter.jpg'),
  supinoLivreInclinado: require('./supino-livre-inclinado.png'),
  crucifixoMaquina: require('./crucifixo-maquina.jpg'),
  tricepsMaquina: require('./triceps-maquina.png'),
  tricepsFrancesPolia: require('./triceps-frances-poliapng.png'),
  abdominalInfraParalela: require('./abdominal-infra-paralela.png'),
  cadeiraExtensora: require('./cadeira-extensora.jpg'),
  cadeiraAbdutora: require('./cadeira-abdutora.jpg'),
  legPress45: require('./leg-press-45.jpg'),
  elevacaoLateralHalter: require('./elevacao-lateral-halter.jpg'),
  remadaAltaPolia: require('./remada-alta-polia.jpg'),
  desenvolvimentoMaquina: require('./desenvolvimento-maquina.jpg'),
};
